# Generated by Django 3.1 on 2020-08-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
