# Generated by Django 3.1 on 2020-08-25 19:40

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='dialog',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reference',
            name='explanation',
            field=models.TextField(max_length=2000),
        ),
    ]
