# Generated by Django 3.1 on 2020-08-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20200821_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='explanation',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reference',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='season',
            name='poster',
            field=models.ImageField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
