# Generated by Django 3.1 on 2020-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20200821_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='explanation',
            field=models.TextField(max_length=1500),
        ),
    ]
