# Generated by Django 3.1 on 2020-08-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20200821_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
